### ISSUE TITLE
Spotify Playlist broke

### ISSUE THREAD

**Issue by misa2610** [kodinerds/repo#12]
Seems that the Spotify Playlist is broke (Version 1.0.10) in Spotitube addon

**Comment by tyl0re** [comment]
What Playlist do you use  (Like --->SpotifyPlaylist--_>Toplist-->Hot Country---> ?
What  Country are you from ?
What Kodi Version do you use?
What Platform (Linux/Windows)
Can you Put Kodi to Debugging Mode , Reproduce the error, and Post the Log.

**Comment by misa2610** [comment]
What Playlist do you use >Hot Country NL (Dutch)
What Country are you from  > Netherlands
What Kodi Version do you use > SPMC 16.4 stable
What Platform > Android
Can you Put Kodi to Debugging Mode > as soon as I can

**Comment by misa2610** [comment]
Hello again. Did you see my log?

**Comment by tstrulw** [comment]
Broke for me as well...
running kodi 6.1 on windows 10. location: IL
I can see sslv3 handshake error against api.

**Comment by tyl0re** [comment]
Short Answer: Will work again with kodi17 cantz be corrected in kodi 16

Long Answer: 
There is an Bug in SSl with sslv1 and sslv2 so ore and ore Websites Disable 1 and 2.
Kodi is using 2.6 Python that has a Bug with 3. 

Since 1,2 are disabled and 3 has a bug Nothing Goes
Kodi17 has that Bug Fixed (New Python Version) so its still working

Since a bug in the python Itself i sorry i cant correct it
