### ISSUE TITLE
Sky Ticket did not play any streams

### ISSUE THREAD

**Issue by Mister-XY** [kodinerds/repo#126]
Since a few days, the sky ticket plugin didn't play any contest from sky ticket.
Here is a log file. I hope is good. [debug.log](https://github.com/kodinerds/repo/files/3612429/debug.log)
Many other people have problem with play the streams.
https://www.kodinerds.net/index.php/Thread/57368-Sky-Ticket-Addon/?postID=545044#post545044

**Comment by panadenbaer** [comment]
Same Problem here on FireTV 4k via Kodi

**Comment by cniweb** [comment]
Same problem with RasperryPi 4, LibreElec 9.1.501 and Kodi 18.4!

**Comment by aeff81** [comment]
I did a little Reverse Engineering using a MITM Proxy.
Looks like Sky changed it's whole infrastructure. That's to hard for applying a quick-and-dirty fix.

If you need any help with repairing the Addon, feel free to contact me.

**Comment by andreas1983a** [comment]
I have the same problem with sky ticket.
I canno't login with username and password.
It's the same problem, i've i login with the sky number or email address.
Have changed the login url?

**Comment by armin884** [comment]
What is best way to some Reverse Engineering on this? How does that MITM Proxy work? Is sky ticket plugin based on the android app?

**Comment by aeff81** [comment]
A MITM-Proxy basically performs a Man-In-The-Middle-Attack (hence it's name). It will terminate the connection of your client and build a new one to the server. This way you can see the whole request in the proxies log file instead of the usual "CONNECT destination.domain".
Since the proxy doesn't have the private key of the original server, it has to create new certificates on the fly. Therefor it needs to create it's own certificate-authority (=CA) certificate which you'll have to declare as a trusted certificate-authority on your client (company networks usually do this by group-policy for virus scanning at their gateway).

Now the recent Android versions don't accept user installed certificates as trusted authorities anymore. That's why I used the Windows (sic!) client of Sky and I don't know what the Android App is doing.

Ok, but let's get started:
This Docker container works pretty well: https://gith**.com/syakesaba/docker-sslbump-proxy but you should add the "strip_query_terms off" directive to the squid.conf.
When you build it, it'll download and compile a recent version of Squid. 
Once built, you can start the container and it'll create a certificate-authority certificate. 
This you'll have to extract from the container without stopping it (because it'll create a new certificate everytime you start it) and import to the trusted-authorities certificate-store of your Windows. 
Then you can set the system proxy to your container and start using sky.
You'll then find the complete request-URL's in the logfile of the container's squid.

**Comment by armin884** [comment]
@aeff81
Thanks for Info. Does the Windows sky client use widevine drm? A friend gave me an m3u8 link with aes-128 drm and said its from sky...

**Comment by ngdio** [comment]
The desktop client uses Cisco VideoGuard so forget that.

I could try and install the app on a phone with Android 7 and then use mitmproxy. Don't have any space for another device left on my account though. Can anyone provide me with one?

**Comment by andreas70** [comment]
Any hope Sky Ticket will ever work again in Kodi?

**Comment by JeansHH** [comment]
+1 ... What a pitty that is plugin is not working anymore :( I do not have windows just linux. And this plugin was the only way to watch sky ticket. So fixing the ticket would be great!
